### PR TITLE
change external report urls to fix on chrome

### PR DESCRIPTION
**Pull request by mava01**
PR to fix this issue - https://github.com/extent-framework/extentreports-csharp/issues/163

### CODE REVIEW

**Review by kingdamo — APPROVED** [review]
Fixes the urls to allow the reports to once again work.

**Comment by andrewlorien** [comment]
This is not only a chrome problem, it affects all browsers.  rawgit.com stopped serving files in late 2019, and the redirect to jsdelivr.net stopped working for older files the week this PR was created.

**Review by andrewlorien — APPROVED** [review]
extentreports.com should be the most reliable source of the css and js files.

**Comment by anilnambiar003** [comment]
We are waiting for this merge. Could you close this PR

**Pull request closed without merging**
